### ISSUE TITLE
error on `npm start`

### ISSUE THREAD

**Issue by Lenic** [wspl/atom-flags#1]
error on `npm start`

``` log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.4.0
3 info using node@v4.2.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle atom-flags@0.0.6~prestart: atom-flags@0.0.6
6 silly lifecycle atom-flags@0.0.6~prestart: no script for prestart, continuing
7 info lifecycle atom-flags@0.0.6~start: atom-flags@0.0.6
8 verbose lifecycle atom-flags@0.0.6~start: unsafe-perm in lifecycle true
9 verbose lifecycle atom-flags@0.0.6~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\MySettings\Documents\GitHub\atom-flags\node_modules\.bin;......
10 verbose lifecycle atom-flags@0.0.6~start: CWD: D:\MySettings\Documents\GitHub\atom-flags
11 silly lifecycle atom-flags@0.0.6~start: Args: [ '/d /s /c', 'node bin/atom-flags' ]
12 silly lifecycle atom-flags@0.0.6~start: Returned: code: 1  signal: null
13 info lifecycle atom-flags@0.0.6~start: Failed to exec start script
14 verbose stack Error: atom-flags@0.0.6 start: `node bin/atom-flags`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid atom-flags@0.0.6
16 verbose cwd D:\MySettings\Documents\GitHub\atom-flags
17 error Windows_NT 10.0.10240
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v4.2.2
20 error npm  v3.4.0
21 error code ELIFECYCLE
22 error atom-flags@0.0.6 start: `node bin/atom-flags`
22 error Exit status 1
23 error Failed at the atom-flags@0.0.6 start script 'node bin/atom-flags'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the atom-flags package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node bin/atom-flags
23 error You can get their info via:
23 error     npm owner ls atom-flags
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by wspl** [comment]
Hello,
There is a solution:

``` sh
# I just fixed some bugs, so you need re-pull this repository.
npm install -g babel-cli
npm install babel-preset-es2015
babel-node --presets es2015 ./lib/main.js
```

This way should be able to work properly.

(I would no longer to maintain this project because I have given up Atom and choose Intellij Idea as the mainly IDE.)

Best wishes.
