### ISSUE TITLE
Usage question, did I utilize the wrong command? 

### ISSUE THREAD

**Issue by AkiChen** [wspl/atom-flags#2]
I'm a windows user and I install the atom-flags through "npm install -g atom-flags". Here comes my problem.

C:\Users\PayenJoe>atom-flags list
C:\Users\PayenJoe\AppData\Roaming\npm\node_modules\atom-flags\lib\index.js:1
(function (exports, require, module, __filename, __dirname) { import readLn from 'readline-sync';

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js](C:UsersPayenJoeAppDataRoamingnpmnode_modulesatom-flagsnode_modulesbabelnode_modulesbabel-corelibapiregisternode.js:214:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\PayenJoe\AppData\Roaming\npm\node_modules\atom-flags\bin\atom-flags:6:1)
    at Module._compile (module.js:435:26)

**Comment by wspl** [comment]
Unfortunately, the application I uploaded to npm could not work. 
Please use following commands to install:

``` sh
// Install git/node/npm first
git clone https://github.com/wspl/atom-flags.git
cd atom-flags
npm install
npm install -g babel-cli
npm install -g babel-preset-es2015
babel-node --presets es2015 ./lib/main.js
```

**Comment by AkiChen** [comment]
Sorry, I have followed your instructions and come up with a new error.
<code>
C:\Main Game\atom-flags>babel-node --presets es2015 ./lib/main.js
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                                                  ^

Error: ENOENT: no such file or directory, open 'C:\Main Game\atom-flags\"C:\Users\PayenJoe\AppData\Local\atom\app-1.2.4\atom.exe"\resources\app.asar'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.exports.readArchiveHeaderSync (C:\Main Game\atom-flags\node_modules\asar\lib\disk.js:79:13)
    at Object.module.exports.readFilesystemSync (C:\Main Game\atom-flags\node_modules\asar\lib\disk.js:105:21)
    at Object.module.exports.extractAll (C:\Main Game\atom-flags\node_modules\asar\lib\asar.js:91:23)
    at new Flags (flags.js:14:43)
    at main.js:74:13
    at locate.js:46:7
    at locate.js:33:28
    at ChildProcess.exithandler (child_process.js:194:7)
</code>

**Comment by AkiChen** [comment]
It has been fixed. In the 16th line of lib/locate.js 

const extRoot = function (stdout) {

  return extRegVal(stdout)
    .replace(/"/g, '')  //This line should be added
    .replace(/\/atom.exe$/, '');
}

**Comment by wspl** [comment]
This bug has been fixed.
