### ISSUE TITLE
安装完了，如何使用？最后一步报错。

### ISSUE THREAD

**Issue by lizhuangs** [wspl/atom-flags#3]
按你说的，安装完了就好使了么。怎么开启direct-write=false？
另外，我安装到最后一步，报错了。我看了下lib目录下有3个js：main.js,locate.js,flags.js。
本人小白，没有折腾过node。
C:\Users\Administrator.atom\atom-flags>babel-node --presets es2015 ./lib/main.js
C:\Users\Administrator\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:327
          throw new Error("Couldn't find preset " + JSON.stringify(val) + " relative to directory " + JSON.stringify(dirname));
          ^

Error: Couldn't find preset "es2015" relative to directory "C:\Users\Administrator\.atom\atom-flags\lib"
    at OptionManager.mergePresets (C:\Users\Administrator\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:327:17)
    at OptionManager.mergeOptions (C:\Users\Administrator\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:287:12)
    at compile (C:\Users\Administrator\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-register\lib\node.js:85:15)
    at loader (C:\Users\Administrator\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-register\lib\node.js:130:14)
    at Object.require.extensions.(anonymous function) [as .js](C:UsersAdministratorAppDataRoamingnpmnode_modulesbabel-clinode_modulesbabel-registerlibnode.js:140:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\babel-cli\lib_babel-node.js:161:27
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\babel-cli\lib_babel-node.js:162:7)

**Comment by wspl** [comment]
``` sh
npm install babel-preset-es2015
```

执行一下上面的命令后再启动试试？

另外，启动之后，输入

``` sh
set redirect-write false
save
```

就可以了。

**Comment by lizhuangs** [comment]
it's ok~Tks~但是设置完了发现菜单字体还没变，很刺眼。不知道有什么方法可以修改菜单的字体？我系统的字体都改了。

**Comment by wspl** [comment]
顶部菜单的字体啊…一般的话 MacType 会渲染到的吧，可能是注入失败了，这问题一般是无解了。

**Comment by lizhuangs** [comment]
那有办法修改菜单的字体么，我想换个字体，但是没发现这方面的资料。windows下面的字体显示效果实是太渣了。

**Comment by wspl** [comment]
我以前用 MacType 替换过系统字体，不过是好久以前的事情了，具体怎么操作已经忘记了，搜索引擎应该可以找到教程的。

**Comment by lizhuangs** [comment]
系统字体已经替换了，就是atom的菜单没有换。。。

**Comment by wspl** [comment]
那应该就是注入失败了…
